"""initial_schema

Revision ID: 559e6298f3eb
Revises: 
Create Date: 2026-04-11 12:17:53.675461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '559e6298f3eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_expectation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_batch_id'), 'recipe', ['batch_id'], unique=True)
    op.create_table('fit_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'needs_review', name='fitstatus'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('normalized_recipe', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_run_recipe_id'), 'fit_run', ['recipe_id'], unique=False)
    op.create_table('fit_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='recommendationseverity'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_change', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fit_run_id'], ['fit_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_recommendation_fit_run_id'), 'fit_recommendation', ['fit_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fit_recommendation_fit_run_id'), table_name='fit_recommendation')
    op.drop_table('fit_recommendation')
    op.drop_index(op.f('ix_fit_run_recipe_id'), table_name='fit_run')
    op.drop_table('fit_run')
    op.drop_index(op.f('ix_recipe_batch_id'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
