"""nullable fit_recommendation severity

Revision ID: 8129f5625e81
Revises: e8f9a0b1c2d3
Create Date: 2026-04-11 16:46:49.625144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8129f5625e81'
down_revision: Union[str, Sequence[str], None] = 'e8f9a0b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fit_recommendation', 'severity',
               existing_type=postgresql.ENUM('info', 'warning', 'error', name='recommendationseverity'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fit_recommendation', 'severity',
               existing_type=postgresql.ENUM('info', 'warning', 'error', name='recommendationseverity'),
               nullable=False)
    # ### end Alembic commands ###
