"""initial_schema

Revision ID: c79ab6ebbafd
Revises: 
Create Date: 2026-04-11 09:23:23.356428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79ab6ebbafd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Text(), nullable=False),
    sa.Column('recipe_name', sa.Text(), nullable=False),
    sa.Column('status_expectation', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('fit_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('agent_model', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('passed', 'failed', 'needs_review', name='fitstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('normalized_recipe', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_run_recipe_id'), 'fit_run', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_fit_run_status'), 'fit_run', ['status'], unique=False)
    op.create_table('fit_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='recommendationseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_change', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fit_run_id'], ['fit_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_recommendation_fit_run_id'), 'fit_recommendation', ['fit_run_id'], unique=False)
    op.create_index(op.f('ix_fit_recommendation_severity'), 'fit_recommendation', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fit_recommendation_severity'), table_name='fit_recommendation')
    op.drop_index(op.f('ix_fit_recommendation_fit_run_id'), table_name='fit_recommendation')
    op.drop_table('fit_recommendation')
    op.drop_index(op.f('ix_fit_run_status'), table_name='fit_run')
    op.drop_index(op.f('ix_fit_run_recipe_id'), table_name='fit_run')
    op.drop_table('fit_run')
    op.drop_table('recipe')
    sa.Enum(name='fitstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recommendationseverity').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
